# Generated by Django 4.0 on 2022-07-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=50)),
                ('identificacion', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('C', 'Cedula'), ('R', 'RUC'), ('P', 'Pasaporte')], max_length=50)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viudo')], max_length=50)),
                ('id_persona', models.IntegerField()),
                ('numero_carga_familiares', models.IntegerField()),
                ('fecha_residencia', models.DateTimeField(auto_now=True)),
                ('tipo_cliente', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
